### ISSUE TITLE
Bar empty after unlocking from 'dm-tool lock'

### ISSUE THREAD

**Issue by alexfrancavilla** [geommer/yabar#105]
Hi, I've recently switched from i3lock without any login-manager to LightDM. When I unlock the screen (locked via `dm-tool lock`), most yabar blocks are empty (display nothing). Blocks of type 'once' are then hidden forever, periodic blocks re-appear after the configured interval and persistent blocks re-appear as soon as they get new input. I couldn't find any relevant logs so far (journalctl/syslogs are clean). It worked perfectly with i3lock before.

Some info about my setup:
- Arch Linux on kernel 4.6.4
- Xorg-server 1.18.4
- bspwm (newest git)
- lightdm 1.18.2 (and its default lightdm-gtk-greeter 2.0.1)
- yabar 0.4.0
- 2 monitors, yabar is configured to the additional monitor via `monitor: "DP2";`

Yabar config is very basic and nothing special (acpi, date, YABAR_WORKSPACES and an echo command with type 'once').

**Comment by jacksgt** [comment]
This is probably the same (core) issue as #71

**Comment by NBonaparte** [comment]
I'm guessing this is fixed now, as the bar redraws on exposure. Please reopen if this is not the case.
