### ISSUE TITLE
xfdesktop goes blank, yabar doesn't appear

### ISSUE THREAD

**Issue by Generator** [geommer/yabar#11]
Using Archlinux with XFCE4 (xfdesktop 4.12.3-1) with composite enable  
Starting yabar xfdesktop goes blank (desktop icons disappear), and yabar doesn't appear

With composite disabled same thing, but there's a black bar
`$ yabar -c example.config`

**Comment by jearbear** [comment]
I'm experiencing the exact same thing in bspwm with compton. When compton is enabled, the bar is completely invisible, without it, I just get a black bar. Using the example config as well.

**Comment by geommer** [comment]
Hi @jearbear, that's exactly what yabar is supposed to do when compton is enabled. If you want to make the bar does not appear with alpha channel use `background-color-rgb` instead of `background-color-argb`. Your may have the same issue as #9 only if you have no text on the bar.

**Comment by jearbear** [comment]
Ok, I briefly looked at issue #9 earlier, but I will give it a deeper look, thanks!

**Comment by Generator** [comment]
Using `background-color-rgb` makes yabar visible.  
Maybe `example.config` should use  `background-color-rgb` instead of `background-color-argb`
