### ISSUE TITLE
[Feature request] Vertical bar

### ISSUE THREAD

**Issue by flannelhead** [geommer/yabar#112]
It would be nice to have a "vertical bar" where the blocks are laid out vertically on the (horizontally narrow) bar. The alignment would be configurable for each block to "top", "center" or "bottom".

The use case for this is e.g. small but wide laptop screens, where vertical space is valuable.

**Comment by flannelhead** [comment]
Just to inform you @geommer, I started looking into this myself. :) I'll open a pull request as soon as I have something to share so you can review the code. This doesn't seem too hard to do. The next step would probably be implementing multiline blocks (think about a vertical list of EWMH desktops, for example).

**Comment by jacksgt** [comment]
Please take a look at #35 
What window manager are you using?
(i3 for example doesn't support vertical bars)

**Comment by flannelhead** [comment]
@jacksgt wow, thanks for the heads-up. I didn't notice that feature request because it was closed. Should've used the search, though... Anyway the thread contains some good points, I'll take those in account.

I'm using bspwm which should be just fine with vertical bars as you can add padding to any screen edge.

**Comment by flannelhead** [comment]
Closing this in favour of continuing the discussion at https://github.com/geommer/yabar/issues/35.
