### ISSUE TITLE
Bug in the workspace in i3wm.

### ISSUE THREAD

**Issue by Sup3r-Us3r** [geommer/yabar#119]
**I have a problem in the Ya Bar workspace using i3wm because with Bspwm not have this problem.**
**For example, when I start i3wm is in workspace 1, but if I want to go now to workspace 7 for example can not, I have to go in order one by one and open a program for me be able to navigate between them.**

**My configuration Yabar if you need ->** https://github.com/Sup3r-Us3r/dotfiles/blob/master/config/yabar/yabar.conf

**Here is a screenshot of Bspwm more it works all right, wanted to use it without problem in the Yabar i3wm.** 
https://github.com/Sup3r-Us3r/dotfiles/blob/master/Screenshots/screenshot12.png

**Comment by Sup3r-Us3r** [comment]
**Resolved, it was perfect.**
_Just leave that way_:

	ya_ws: {
		exec: "i3-msg -t get_workspaces | jq '.[] | select(.focused).num'";
		align: "left";
		background-color-rgb:0xFF6CAA;
                foreground-color-rgb: 0x303030;
                underline-color-rgb:0x848484;
                type: "periodic";
		interval: 0.2;
		fixed-size: 40;
#		internal-option1: "I II III IV V VI VII VIII IX X";
	}

**Comment by BurningFury** [comment]
Was having the same problem myself until I saw this.
However, now it only displays numbers (1 2 3 4) instead of Icons (    )
How do you make it show the Icons instead of the numbers?
Need to change something in the code?

**Comment by soyuka** [comment]
@BurningFury use    ` exec: "i3-msg -t get_workspaces | jq '.[] | select(.focused).name'";` to get the workspace name. If it's set in i3 as an icon you'll get that.

**Comment by NBonaparte** [comment]
Closing, as issue seems to be resolved.
