### ISSUE TITLE
urgent desktop

### ISSUE THREAD

**Issue by pjhalsli** [geommer/yabar#121]
I love yabar and i'm using it in both herbstluftwm and Bspwm.

One thing though - would it be possible to add more workspaces/rags or whatever they are called.   The only thing I'm missing is so i could have urgent desktop.  Say I 'm reading the news on tag 2 and get tagged on irc on another workspace. it would be nive to know thi withou have to check  it all the time. The block for the urgent desktop could just turn to red or something so it would be very easy to see something needs your attention.  Even tint2 have this feature so I cant imagine it's too hard to implement.  Might ofc be wrong on that one.

Anyway - thanks for all the time and effort you've put into this project. For me it's "almost" the perfect bar

**Comment by NBonaparte** [comment]
We are working on this currently on the [dev_workspaces](https://github.com/geommer/yabar/tree/dev_workspaces) branch.

**Comment by sqozz** [comment]
I don't want to advertise but i wrote a script which is a little bit more advanced in handling the workspaces of i3 at least. If other WMs also provide some IPC socket it should be easy to adopt it to your needs.

**Comment by pjhalsli** [comment]
WOW Time flies.  Been playing around with some other bars lately,  but like I wrote when I opened this issue. This is almost perfection.  Now I'm just looking forward to a new stable release - 0.5 or maybe even 1.0??
I'll close this now - and thanks again for all the time and effort you've put in this project.
