### ISSUE TITLE
 (yabar) crashed and dumped core.

### ISSUE THREAD

**Issue by ibrokemypie** [geommer/yabar#123]
Dec 16 16:18:05 archTOP systemd-coredump[7878]: Process 7876 (yabar) of user 0 dumped core.
                                                
                                                Stack trace of thread 7876:
                                                #0  0x0000000000403fe5 ya_config_parse (yabar)
                                                #1  0x0000000000405625 ya_init (yabar)
                                                #2  0x00000000004037dd main (yabar)
                                                #3  0x00007f487bb97291 __libc_start_main (libc.so.6)
                                                #4  0x000000000040386a _start (yabar)
-- Subject: Process 7876 (yabar) dumped core
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 7876 (yabar) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.

**Comment by jacksgt** [comment]
From the stack trace is seems yabar's config parser crashed. Could you please post your full configuration file?

**Comment by barisbalic** [comment]
Over a year old, worth closing @jacksgt ?
