### ISSUE TITLE
Cant install in Fedora 

### ISSUE THREAD

**Issue by NeuroWinter** [geommer/yabar#125]
I have cloned and installed the required dependencies, however I still get this error when making

![screenshot from 2017-02-02 21-37-03](https://cloud.githubusercontent.com/assets/7663857/22542176/6a32c794-e98f-11e6-90bd-ccd69b0d0cfc.png)

**Comment by jacksgt** [comment]
You don't seem to have a C compiler (`cc`) installed. Please do so by installing either gcc, clang or some other C compiler:
```
yum install gcc
```

**Comment by NeuroWinter** [comment]
Ahh great thank you that fixed my 1st issue, however I now get this:

![screenshot from 2017-02-02 21-58-08](https://cloud.githubusercontent.com/assets/7663857/22542770/6720b432-e992-11e6-859e-a0b27f570d80.png)

**Comment by jacksgt** [comment]
Please try installing `xcb-util-wm-devel`, that should fix the issue.

**Comment by NeuroWinter** [comment]
Great that fixed it thank you so much :) now to figure out how to replace i3bar with yabar :)

**Comment by jacksgt** [comment]
Glad to hear its fixed - I will add it to the dependencies.

Please close this issue then @NeuroWinter

**Comment by NeuroWinter** [comment]
On a new install I am now getting this 

![Uploading Screenshot from 2017-02-05 19-33-02.png…]()

**Comment by jacksgt** [comment]
You are getting *what* exactly? (The link to your Screenshot 2017-02-05 19-33-02.png is not working)

**Comment by jacksgt** [comment]
Since the original issue was resolved (and there is now follow up on your second problem), I'm closing this issue.

Feel free to open a new when any problems come up.

**Comment by NeuroWinter** [comment]
Sure thing thank you!
