### ISSUE TITLE
Yabar stays in background, doesn't adjust my tiling in BSPWM.

### ISSUE THREAD

**Issue by MeowMeowKins** [geommer/yabar#130]
Basically the title, I am using

- Archlinux 4.9.11-1
- BSPWM 0.9.2 ([config](https://psycho.space/p/1b915))
- Yabar v0.4.0-80-gbc091f5 ([config](https://psycho.space/p/baf52))
- Compton v0.1_beta2.5 ([config](https://psycho.space/p/dcf73))

The problem that happens is when I tile my things, it for some reason overlaps the bar.

Little story:
I tried yabar with the normal ([AUR package](https://aur.archlinux.org/packages/yabar/)) but that started crashing because of instability and some configurations not properly loading in it, but the bar would easily react properly to the tiling and it wouldn't allow anything to be overlapping it (unless fullscreen), which was the nice thing about it.

So I turned to the ([AUR package](https://aur.archlinux.org/packages/yabar-git/)) that fetches the updates from git so I can add some more functionality to the bar, it fixed my crashes but now shows me things like this: 

[Screenshot of said overlapping.](https://psycho.space/u/45ce7.png)

Thank you and Kind Regards,

MeowMeowKins
Thu, 23rd of Feb, 13:29

**Comment by NBonaparte** [comment]
Sorry, override redirect broke it. I've reverted that part back in 63f0bb2.
Just so you know, you can use `bspc config top_padding` to set the top padding.

**Comment by NBonaparte** [comment]
I believe this has been fixed now, as all of the other issues reporting the same problem have been resolved. Feel free to reopen this issue if it still is broken.
