### ISSUE TITLE
Bar On Multiple Monitors

### ISSUE THREAD

**Issue by ibrokemypie** [geommer/yabar#132]
I have not been able to find any reference to this, and simply defining two monitors in the config causes yabar not to start, so I am assuming this is not implemented.
May we have the ability to define multiple monitors, perhaps with an all or wildcard option, in a single bar? I know making multiple bars works, but this makes the config a hell of a lot bigger and messier than it needs to be if you wish to simply duplicated the bar on multiple/all screens exactly the same.
Thanks!

**Comment by NBonaparte** [comment]
You can do:
```
bar2:{
    inherit-all: "bar1";
    monitor: "<insert other monitor>"
}
```
where `bar-list = ["bar1", "bar2"];` which shouldn't lengthen the config too much. It appears that currently external modules don't work when inheriting, so I'll try to fix that.

**Comment by ibrokemypie** [comment]
Perfect, was not aware of that option, and this solves it perfectly, so will close now, thanks!
