### ISSUE TITLE
YABAR_DISKSPACE?

### ISSUE THREAD

**Issue by DGalt** [geommer/yabar#138]
Been trying to get yabar set up (really nice application, big fan so far), working from the example.conf in the examples folder in this repo. Most things seem to be working besides the diskspace block. 

Getting:
`No type is defined for block: ya_diskspace. Skipping this block...`

Looking through the internal blocks in `ya_intern.c` I don't see anything for `YABAR_DISKSPACE`

Is this just not available right now, or am I missing something? 

I'm on Arch, installed the AUR yabar-git package.

**Comment by NBonaparte** [comment]
Good catch, sorry about that. It's in a [different branch](https://github.com/geommer/yabar/tree/transfer-disk-blk) right now, but it will be merged soon. Originally we had both the config change and disk space block on a fork and transferred them over here individually at different times, which caused some desynchronization.

**Comment by DGalt** [comment]
OK, that's what I figured, just wanted to make sure.

**Comment by DGalt** [comment]
Just FYI, there's also a type in `ya_volume` block. 

The line for `internal-option2` has a `;` between `Master` and `0`

**Comment by jacksgt** [comment]
@DGalt The semicolon space mismatch was my mistake - fixed in a2c8d036aafda77d5e25705151c04ff0b4c14a50

**Comment by NBonaparte** [comment]
I've merged the block into `master`, so I'll close this now.
