### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [geommer/yabar#14]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/geommer/yabar/blob/7ffc1e19d6d1712a56483ef4a9b928c752cf5c12/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](https://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by wildefyr** [comment]
Both could be considered bloat, especially for a small project such as this, but over the two, autotools would be better. CMake is considered to be pretty rubbish.
