### ISSUE TITLE
yabar_workspace: Only updates if some program is open on previous workspace

### ISSUE THREAD

**Issue by Narrat** [geommer/yabar#147]
Kinda weird to describe.
Example 1: Five workspaces and on the first two of them are open programs. the yb_ws block will change from 1 to 3 if I'm cycling through the workspaces. For the rest it stays with the name of the third workspace.

Example 2: Five workspaces, staying on Two with an open program, hop to Workspace Four (no program there), yb_ws updates to the name of workspace four. Hopping from four to five or three (no programs open there too) and the name displayed is from workspace four.
Hopping to a workspace with an open program there will also result in the correct name displayed.

Opening a program on those empty workspaces will update the yb_ws to the correct name.

![bla4](https://cloud.githubusercontent.com/assets/2787518/24879813/55757cba-1e38-11e7-84cc-b467e4422556.png)
Instead of an epsilon there is delta displayed

Edit:

Correct display:
![bla5](https://cloud.githubusercontent.com/assets/2787518/24879937/bdbda298-1e38-11e7-911f-605498e5b630.png)

Probably a video would be more fitting.. hm

**Comment by NBonaparte** [comment]
What WM are you using?

**Comment by Narrat** [comment]
Ah, I knew I forgot something.
This is openbox

**Comment by NBonaparte** [comment]
Thanks, fixed.

What is the output of `xprop -root | grep _NET`? (Run it right after switching workspaces as per your examples.) I have a hunch that openbox might do something funky with the EWMH properties.

**Comment by Narrat** [comment]
Switched that way, that on the third workspace the wrong name was displayed (the one from the fourth)
Results from two different programs, as openbox also provides a tool for querying xproperties

```sh
$ sleep 3 && obxprop --root | grep _NET
_NET_ACTIVE_WINDOW(WINDOW) = 0
_NET_CLIENT_LIST(WINDOW) = 6291459, 20971523, 25165827, 27262979, 23068673
_NET_SHOWING_DESKTOP(CARDINAL) = 0
_NET_CURRENT_DESKTOP(CARDINAL) = 2
_NET_DESKTOP_NAMES(UTF8_STRING) = "Alpha", "Beta", "Gamma", "Delta", "Epsilon"
_NET_WORKAREA(CARDINAL) = 0, 30, 1680, 1020, 0, 30, 1680, 1020, 0, 30, 1680, 1020, 0, 30, 1680, 1020, 0, 30, 1680, 1020
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 5
_NET_DESKTOP_GEOMETRY(CARDINAL) = 1680, 1050
_NET_CLIENT_LIST_STACKING(WINDOW) = 6291459, 25165827, 20971523, 27262979, 23068673
_NET_SUPPORTED(ATOM) = _NET_SUPPORTING_WM_CHECK, _NET_WM_FULL_PLACEMENT, _NET_CURRENT_DESKTOP, _NET_NUMBER_OF_DESKTOPS, _NET_DESKTOP_GEOMETRY, _NET_DESKTOP_VIEWPORT, _NET_ACTIVE_WINDOW, _NET_WORKAREA, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_DESKTOP_NAMES, _NET_CLOSE_WINDOW, _NET_DESKTOP_LAYOUT, _NET_SHOWING_DESKTOP, _NET_WM_NAME, _NET_WM_VISIBLE_NAME, _NET_WM_ICON_NAME, _NET_WM_VISIBLE_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_STRUT, _NET_WM_STRUT_PARTIAL, _NET_WM_ICON, _NET_WM_ICON_GEOMETRY, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ALLOWED_ACTIONS, _NET_WM_WINDOW_OPACITY, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_STATE, _NET_WM_STATE_MODAL, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SHADED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_MOVERESIZE_WINDOW, _NET_WM_MOVERESIZE, _NET_WM_USER_TIME, _NET_FRAME_EXTENTS, _NET_REQUEST_FRAME_EXTENTS, _NET_RESTACK_WINDOW, _NET_STARTUP_ID, _NET_WM_SYNC_REQUEST, _NET_WM_SYNC_REQUEST_COUNTER, _NET_WM_PID, _NET_WM_PING, _KDE_WM_CHANGE_STATE, _KDE_NET_WM_FRAME_STRUT, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _OB_WM_ACTION_UNDECORATE, _OB_WM_STATE_UNDECORATED, _OPENBOX_PID, _OB_THEME, _OB_CONFIG_FILE, _OB_CONTROL, _OB_VERSION, _OB_APP_ROLE, _OB_APP_TITLE, _OB_APP_NAME, _OB_APP_CLASS, _OB_APP_GROUP_NAME, _OB_APP_GROUP_CLASS, _OB_APP_TYPE
_NET_SUPPORTING_WM_CHECK(WINDOW) = 4194827

$ sleep 3 && xprop -root | grep _NET  
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x0
_NET_CLIENT_LIST(WINDOW): window id # 0x600003, 0x1400003, 0x1800003, 0x1a00003, 0x1600001, 0x800003
_NET_SHOWING_DESKTOP(CARDINAL) = 0
_NET_CURRENT_DESKTOP(CARDINAL) = 2
_NET_DESKTOP_NAMES(UTF8_STRING) = "Alpha", "Beta", "Gamma", "Delta", "Epsilon"
_NET_WORKAREA(CARDINAL) = 0, 30, 1680, 1020, 0, 30, 1680, 1020, 0, 30, 1680, 1020, 0, 30, 1680, 1020, 0, 30, 1680, 1020
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 5
_NET_DESKTOP_GEOMETRY(CARDINAL) = 1680, 1050
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x1800003, 0x1400003, 0x1a00003, 0x800003, 0x600003, 0x1600001
_NET_SUPPORTED(ATOM) = _NET_SUPPORTING_WM_CHECK, _NET_WM_FULL_PLACEMENT, _NET_CURRENT_DESKTOP, _NET_NUMBER_OF_DESKTOPS, _NET_DESKTOP_GEOMETRY, _NET_DESKTOP_VIEWPORT, _NET_ACTIVE_WINDOW, _NET_WORKAREA, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_DESKTOP_NAMES, _NET_CLOSE_WINDOW, _NET_DESKTOP_LAYOUT, _NET_SHOWING_DESKTOP, _NET_WM_NAME, _NET_WM_VISIBLE_NAME, _NET_WM_ICON_NAME, _NET_WM_VISIBLE_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_STRUT, _NET_WM_STRUT_PARTIAL, _NET_WM_ICON, _NET_WM_ICON_GEOMETRY, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ALLOWED_ACTIONS, _NET_WM_WINDOW_OPACITY, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_STATE, _NET_WM_STATE_MODAL, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SHADED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_MOVERESIZE_WINDOW, _NET_WM_MOVERESIZE, _NET_WM_USER_TIME, _NET_FRAME_EXTENTS, _NET_REQUEST_FRAME_EXTENTS, _NET_RESTACK_WINDOW, _NET_STARTUP_ID, _NET_WM_SYNC_REQUEST, _NET_WM_SYNC_REQUEST_COUNTER, _NET_WM_PID, _NET_WM_PING, _KDE_WM_CHANGE_STATE, _KDE_NET_WM_FRAME_STRUT, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _OB_WM_ACTION_UNDECORATE, _OB_WM_STATE_UNDECORATED, _OPENBOX_PID, _OB_THEME, _OB_CONFIG_FILE, _OB_CONTROL, _OB_VERSION, _OB_APP_ROLE, _OB_APP_TITLE, _OB_APP_NAME, _OB_APP_CLASS, _OB_APP_GROUP_NAME, _OB_APP_GROUP_CLASS, _OB_APP_TYPE
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x40020b
```

At least _NET_CURRENT_DESKTOP has the right value

**Comment by NBonaparte** [comment]
Does 8d0fef3 fix this? Since `_NET_CURRENT_DESKTOP` changes properly, the block should theoretically update as well.

Also (even if the fix works) could you try doing `xprop -root -spy` (or the `obxprop` equivalent) and see if `_NET_ACTIVE_WINDOW` changes normally? Without the fix, the handler just checks for `_NET_ACTIVE_WINDOW`, and if it doesn't change, then the block doesn't update, which might be the source of the issue.

**Comment by Narrat** [comment]
Unfortunately it doesn't change the behaviour even with 8d0fef3.

And regarding _NET_ACTIVE_WINDOW behaviour. If there is an ID (one of those listed in _NET_CLIENT_LIST) on a workspace, the fitting ID is shown there.
And if changes are tracked, well, that would explain the behaviour. Switching to an empty workspace produces a change, as it switches from $ID to 0. On further switches to empty workspaces there is no change as it stays at 0.

**Comment by NBonaparte** [comment]
Sorry, it looks like I forgot to get the current workspace in the previous commit. Does a1bd267 work for you?

**Comment by Narrat** [comment]
Yes, with a1bd267 applied it is working. Thanks

Closing this issue, as it is resolved

**Comment by KmBKeef** [comment]
Hmm still.. it doesn't update unless the previous workspace got something

**Comment by KmBKeef** [comment]
![screenshot from 2017-07-20 16-38-48](https://user-images.githubusercontent.com/23081518/28437865-2b0b6c1a-6d6a-11e7-8fd8-270ef2380d8f.png)
![screenshot from 2017-07-20 16-39-01](https://user-images.githubusercontent.com/23081518/28437866-2c5f7f02-6d6a-11e7-9eab-7b7ffc5449e7.png)

**Comment by Narrat** [comment]
What does 
``` sh
yabar -v
```
print and what window manager do you use? To me it kinda looks like i3 and the reported issue was more or less specific to openbox

**Comment by KmBKeef** [comment]
yabar's version is:
`yabar v0.4.0-146-g9779a5e`

And I am using i3-gaps

**Comment by Narrat** [comment]
Maybe you could take a look at the xprop values, like previously mentioned ( https://github.com/geommer/yabar/issues/147#issuecomment-293108367 ).
As far as I know i3 had some issues with some EWMH values (like https://github.com/i3/i3/issues/938 )

Are those workspaces existing? Years ago when I tried i3 workspaces were created on the fly

**Comment by KmBKeef** [comment]
You are right, they get removed when you leave them empty..but surely there is  a way for yabar to figure out what workspace am i on. since i travel between them using i3's shortcut ($mod 1, $mod 2, $mod 3...)



```
$ sleep 3 && xprop -root | grep _NET

_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0
_NET_DESKTOP_NAMES(UTF8_STRING) = "1 # \"Firefox\"", "5"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 2
_NET_CURRENT_DESKTOP(CARDINAL) = 1
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x0
_NET_CLIENT_LIST(WINDOW): window id # 0xa00007, 0x1400010, 0x140003d
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0xa00007, 0x1400010, 0x140003d
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_WM_NAME, _NET_WM_VISIBLE_NAME, _NET_WM_MOVERESIZE, _NET_WM_STATE_STICKY, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_STATE_MODAL, _NET_WM_STATE_HIDDEN, _NET_WM_STATE, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_DESKTOP, _NET_WM_STRUT_PARTIAL, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_CURRENT_DESKTOP, _NET_NUMBER_OF_DESKTOPS, _NET_DESKTOP_NAMES, _NET_DESKTOP_VIEWPORT, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW
_NET_WM_NAME(UTF8_STRING) = "i3"
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x200063
```

**Comment by Narrat** [comment]
Well, at least you could propably write your own script and add a custom block to the config which replaces the internal workspace one .
For further discussion I would suggest to open a new issue, as this was a specific and solved problem. And you want a feature included, which is currently not covered by yabar.

But maybe the whole issue is solved by static workspaces if that is possible?

**Comment by KmBKeef** [comment]
unfortunately it turned out that i3 devs hate static workspaces...

hmm alright thanks for your time and effort
