### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [geommer/yabar#15]
I would like to point out that an identifier like "[`_YABAR_H`](https://github.com/geommer/yabar/blob/7ffc1e19d6d1712a56483ef4a9b928c752cf5c12/src/yabar.h#L9)" [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by geommer** [comment]
Thank you for the issues, I will begin with this issue because it is the easiest :smiley:.

**Comment by elfring** [comment]
Which commit will fix this issue?

**Comment by geommer** [comment]
It was embedded in this [commit](https://github.com/geommer/yabar/commit/c9c0e709b18daf512e12733bb56a0bb703cc98d9#diff-e3436ee62e73bbcdc6c38599e33d84f4R10).

**Comment by elfring** [comment]
Thanks for [your improvement of an affected include guard](https://github.com/geommer/yabar/commit/c9c0e709b18daf512e12733bb56a0bb703cc98d9#diff-e3436ee62e73bbcdc6c38599e33d84f4L9 "Deletion of an underscore").
