### ISSUE TITLE
i3: no background color if workspace is empty

### ISSUE THREAD

**Issue by apognu** [geommer/yabar#151]
I noticed that when yabar starts and the current workspace has no window open, the bar background is transparent (black without compton, really transparent with it), which happens, for instance, when I log in.

If I open a window and reload i3, the background displays properly.

```
% yabar -v
yabar v0.4.0-145-g0a8d11a
```

![without_window](https://cloud.githubusercontent.com/assets/3017182/25566979/3fff5174-2de4-11e7-9aad-efcc861922b1.png)
![with_window](https://cloud.githubusercontent.com/assets/3017182/25566978/3ffb9eb2-2de4-11e7-8f73-66938e1c4ab2.png)

**Comment by jacksgt** [comment]
This is actually a feature, see [no-window-color under bar-specific options](doc/yabar.1.asciidoc).

Please provide your config file.
