### ISSUE TITLE
Can't build yabar

### ISSUE THREAD

**Issue by SolarAquarion** [geommer/yabar#154]
cc -o yabar src/ya_parse.o src/ya_exec.o src/ya_draw.o src/ya_main.o src/intern_blks/ya_intern.o -liw -lxcb -lpthread -lxcb-randr -lxcb-ewmh -lxcb-icccm -lm `pkg-config --libs pango pangocairo libconfig gdk-pixbuf-2.0 alsa`
src/intern_blks/ya_intern.o: In function `ya_int_date':
ya_intern.c:(.text+0x57): undefined reference to `ya_setup_prefix_suffix'
src/intern_blks/ya_intern.o: In function `ya_int_uptime':
ya_intern.c:(.text+0x17b): undefined reference to `ya_setup_prefix_suffix'
src/intern_blks/ya_intern.o: In function `ya_int_loadavg':
ya_intern.c:(.text+0x399): undefined reference to `ya_setup_prefix_suffix'
src/intern_blks/ya_intern.o: In function `ya_int_volume':
ya_intern.c:(.text+0x5c1): undefined reference to `ya_setup_prefix_suffix'
src/intern_blks/ya_intern.o: In function `ya_int_diskspace':
ya_intern.c:(.text+0xa15): undefined reference to `ya_setup_prefix_suffix'
src/intern_blks/ya_intern.o:ya_intern.c:(.text+0xd54): more undefined references to `ya_setup_prefix_suffix' follow
collect2: error: ld returned 1 exit status

**Comment by NBonaparte** [comment]
Should be fixed now, please check.
