### ISSUE TITLE
Can't build yabar on Debian jessie

### ISSUE THREAD

**Issue by romzie** [geommer/yabar#155]
cc -o yabar src/ya_parse.o src/ya_exec.o src/ya_draw.o src/ya_main.o src/intern_blks/ya_intern.o -liw -lxcb -lpthread -lxcb-randr -lxcb-ewmh -lxcb-icccm -lm `pkg-config --libs pango pangocairo libconfig gdk-pixbuf-2.0 alsa`
src/ya_parse.o: dans la fonction « ya_config_parse »:
ya_parse.c:(.text+0x4ca): référence indéfinie vers « config_setting_lookup »
ya_parse.c:(.text+0xbbe): référence indéfinie vers « config_setting_lookup »
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'yabar' failed
make: *** [yabar] Error 1

ps: I installed all the requirements as the instructions mentionned

**Comment by nyancol** [comment]
As mentioned in [#38](https://github.com/geommer/yabar/issues/38), an upgrade to libconfig-dev >=1.5 from testing fixed the problem.
Please, next time you raise an issue, check if there is already one closed that could answer your question.
