### ISSUE TITLE
Does not show Battery usage!

### ISSUE THREAD

**Issue by lordjbs** [geommer/yabar#158]
Hello. Im using a Packard Bell EasyNote and battery usage doesnt work.
![shot_2017-08-11_16-52-01](https://user-images.githubusercontent.com/23281889/29218567-80114a02-7eb5-11e7-8af3-91cf3b8c420b.png)
Code is: https://gist.github.com/lordjbs/d23c9b85a8b0f86e727c0ca26ed22464

**Comment by Narrat** [comment]
Any information where your battery information is located?
Normally the location is in `/sys/class/power_supply/` with BAT0/capacity having the information. Any other path for you?

**Comment by lordjbs** [comment]
Yeah, it's BAT1

**Comment by Narrat** [comment]
So what happens if you change the internal-option1 to BAT1?

**Comment by pmatos** [comment]
@lordjbs like @narrat said, you have a broken config file. Use `internal-option1: "BAT0";`
I think this can be closed.
