### ISSUE TITLE
Is it possible in addition to pango text formatting to somehow execute commands on mouse clicks?

### ISSUE THREAD

**Issue by ervasive** [geommer/yabar#164]
Currently Yabar allows us to assign commands for the whole block with `command-button{1-5}`, but in some cases it may be not flexible enough.

Here's how some other status bars out there implement this kind of feature.

[xmobar](https://github.com/jaor/xmobar)
```
<action=`command` button=12345>
```

[dzen](https://github.com/robm/dzen)
```
^ca(BTN, CMD) ... ^ca() 
```

[polybar](https://github.com/jaagr/polybar/wiki/Formatting)
```
%{A1:command:} clickable text %{A}
```

[lemonbar](https://github.com/LemonBoy/bar)
```
%{A:reboot:} Click here to reboot %{A}
```

Thanks.

**Comment by NBonaparte** [comment]
This isn't possible right now, but could be something to be implemented in the future. The best workaround currently would be to use a script to check `$YABAR_CLICK_X/Y` and see if it is in range.
