### ISSUE TITLE
Debian package does not support gaps

### ISSUE THREAD

**Issue by romzie** [geommer/yabar#179]
Installed on Debian 9.3 with `apt install yabar` (v0.4.0-1).

I tried to use the example configuration file and the gaps are not created at all, even with larger values.

Everything else seems to be working fine except the block center alignment with a positive slack size as mentioned in issue#156.
  
Edit: edited the title because the internal blocks are not found when I launch yabar but maybe I missed an option.

**Comment by Ma27** [comment]
When you have a look at the releases (https://github.com/geommer/yabar/releases) you'll notice that `0.4.0` is fairly behind `master` which contains all the new features.
Therefore it might be the best if you build this bar from master, however you have to ask @NBonaparte for a new release as I don't have any commit/tagging permissions here.

**Comment by gh67uyyghj** [comment]
Yes, the last stable or tagged version was released long ago and has many old bugs that were fixed later, please author or contributors release another version. The current master branch is already mature enough for v1.0

**Comment by romzie** [comment]
Closing this issue since a new release is probably never coming.
