### ISSUE TITLE
Single bar not displaying on multiple-monitors.

### ISSUE THREAD

**Issue by barisbalic** [geommer/yabar#182]
I have noticed that if I specify two monitors for a single bar, it only appears on the first specified monitor, however if I create a separate bar and place one on each monitor, they both appear.  This seems contrary to the documentation?

**Comment by NBonaparte** [comment]
The monitor option goes through every monitor listed and checks if it exists, and if so, draws on that monitor. This is the intended functionality as shown in the documentation.

**Comment by barisbalic** [comment]
Sorry that was pure ignorance, I only read as far as "The default value (when this option is not provided) is the first active monitor".  Please accept my apologies.
