### ISSUE TITLE
support for i3bar?

### ISSUE THREAD

**Issue by carnager** [geommer/yabar#21]
will yabar support usage via the "status_command" so that we can have the benefit of i3bars systray?

**Comment by geommer** [comment]
Yabar actually replaces i3bar with its combination with i3blocks/i3pystatus. You can just remove or comment everything in
`bar{
   //
}`
and yabar should work just as fine.

**Comment by carnager** [comment]
but it doesn't come with an inbuilt systray/workspace switcher

**Comment by geommer** [comment]
Yes, because yabar is wm-agnostic. If i3 provides a command to show info about workspaces like bspwm, you can use it to show the workspaces on the bar.

**Comment by craftyguy** [comment]
That's rather inconvenient and messy though, and there's still no viable replacement for the systray... is it not possible to have yabar integrate with i3bar rather than outright replace it?

**Comment by Lindenk** [comment]
This seems to be more of a problem with i3 and i3bar rather than yabar.

**Comment by wildefyr** [comment]
Long ago when I ran i3 I had the same issue, eventually I came up with [this ruby script](https://gist.github.com/wildefyr/68984ab4bb590f4aab61) to produce the workspaces names in plain text, which could then be used by (i think) conky at the time, but it should produce the correct output for any bar.

**Comment by Traverse** [comment]
I made a quick and dirty script using PHP which is similar to yours but I was wondering if you can for example change the colors for the focused workspace this way and if so how would I go about doing that?

**Comment by wildefyr** [comment]
Consult the i3-msg manpage. There might be a command switch that'll return the currently focused workspace (and if there isn't, submit an issue to i3)

**Comment by tombessems** [comment]
I can already check if it's the focused workspace it's more about how do I get it to actually output a color tried pango markup but that's not doing anything

**Comment by Traverse** [comment]
I can already check if it's the focused workspace it's more about how do I get it to actually output a color tried pango markup but that's not doing anything so not sure how I'd go about doing it.

**Comment by wildefyr** [comment]
Ah, I'm not sure on yabar's specifics there... If there's not a way to output a specific color in text from a script I won't be using this anytime soon.

**Comment by Lindenk** [comment]
Pongo support changing color using text: `<span foreground="red">This text is red</span> and this is the default color`

**Comment by Traverse** [comment]
That's basically what I did and it's outputting the tags as well instead of making the text red, it's probably an error on my part doing something stupid but at this point I have no clue what it'd be.

**Comment by aanc** [comment]
@Traverse, I think you forgot to activate pango-markup in the bloc with `pango-markup: true;`

I managed to have workspace display in yabar with this bash script: https://bpaste.net/raw/94f0d550a76f 
You'll need `jq` to have it working correctly, as I use it to parse the JSON produced by the `i3-msg` command. If you pass a monitor name to the script, it will only display workspaces which are on that monitor. 
I still need to figure out how to make it clickable (i mean, a click on a workspace number should switch to the workspace), and I'm also not happy with the update latency of the widget (as it is a periodic bloc on my current setup, it can take up to 1 sec to have it updated when i switch workspaces)

**Comment by Traverse** [comment]
@aanc Yep that's indeed what I forgot, got it working now. As for your other points the update latency is bugging me as well, sometimes it even feels longer than 1 second for it to update. As for the clicking part, if you can retrieve the number you clicked on it might be doable as you'd just need to execute `i3-msg workspace` plus the number.
