### ISSUE TITLE
Add an 'extends' option to bars

### ISSUE THREAD

**Issue by Lindenk** [geommer/yabar#25]
For multi-monitor setups, most of the bar configurations have quite a bit in common but currently must be specified seperately. I propose an `extends` option that will insert the specified bar's configuration into the new bar's configuration.

**Comment by geommer** [comment]
Thank you @Lindenk, I think you are right about the problem, but I propose we can better solve this problem bu using global config that are the same level of indentation as the entry `bar-list`. Inside the bar level config, the config entries, if stated, should override the global config entries.
Example:
`
font: "Font1"

bar-list: ["bar1", "bar2"];

bar1:{

 //no font entry defined. use "Font1"

}

bar2: {

  font : "Font2"
//here Font2 overrides Font1

}
`

However, I suspect this would be useful for all bar-specific options. I will keep this issue open until we reach an agreeable solution.

**Comment by Lindenk** [comment]
Yeah, that would also solve the issue. The downside would be that it wouldn't be easy to set up two completely seperate bars that are duplicated across a few monitors. I'd rather go with explicit inheritance (using something like `extends`) over nested inheritance, but as long as we have a working solution, I don't think it'll make much of a difference.

**Comment by geommer** [comment]
Well, that took more time than I had first thought. Please go to the new README to know how the `inherit` options work. Of course I will reopen the issue if the solution is still missing something.

**Comment by Lindenk** [comment]
Wow that was fast. It looks just like what I was thinking. I'll try it out tonight.
