### ISSUE TITLE
Support for an existing configuration format

### ISSUE THREAD

**Issue by Lindenk** [geommer/yabar#26]
I propose we add support for using either YAML or JSON for the configuration syntax to improve consistancy between tools and to make it easier to implement any moderately intricate configuration features (such as #25). 

This could also be added in addition to the current format by either using a new command line flag or by checking the configuration file's extention.

**Comment by geommer** [comment]
I think no need to keep this issue open now since #25 is closed now. Actually, most nesting and leveling tricks can be efficiently implemented using libconfig.
