### ISSUE TITLE
Feature Request: Add borders

### ISSUE THREAD

**Issue by dialuplama** [geommer/yabar#28]
It would be nice if yabar could draw borders around itself. I know that i can achieve this by launching two instances of yabar. But I would like to avoid this trick.

Here what i mean:
https://i.imgur.com/Xpskb0Q.png

**Comment by geommer** [comment]
I really like the idea and it does cause a very slight bloat. Please check the README to understand how the new options for borders work.

**Comment by dialuplama** [comment]
Thank you!
