### ISSUE TITLE
Bar width and offset options

### ISSUE THREAD

**Issue by Lindenk** [geommer/yabar#3]
Fixed width bars could be placed offset on the top and bottom of the screen to provide a more artistic feel. Also, it would allow users to set up multi-monitor configurations (although built in multi-monitor support would be amazing as well, but that's a seperate issue).

**Comment by geommer** [comment]
For the offset issue, if I understand you right and please correct me if I am wrong, it is already implemented using `gap-horizontal` and `gap-vertical` in the bar-specific options (have a look again at the readme). For the multi-monitor thing, this will be a priority for me in the incoming days.
