### ISSUE TITLE
spectrwm issue?

### ISSUE THREAD

**Issue by AffableZonkey** [geommer/yabar#30]
Hello - using spectrwm V2.7.2 on Fedora 23. I am having trouble getting yabar to display on all workspaces? Maybe I dont understand the documentation. I've tried reserving screen in my .spectrwm.conf, not reserving a screen, and launching yabar with the baraction in .spectrwm.conf and as a script that calls yabar.

Calling yabar in .xinitrc starts yabar fine on WS 1. Any idea what I could be doing wrong (other than using spectrwm :)

**Comment by cserb** [comment]
@AffableZonkey did you solve your problem? If so, how?

**Comment by AffableZonkey** [comment]
I did not solve the problem. I moved on and should've closed the issue.
