### ISSUE TITLE
Can't render bar on other monitor

### ISSUE THREAD

**Issue by aanc** [geommer/yabar#36]
Hi,

I tried the experimental randr support, but it seems not to be working on my setup, the 2 bars are showing on the primary monitor. I am on a laptop with closed screen on a docking station, and 2 external monitors. LVDS1 is my laptop built-in screen, which is connected but not used. The 2 other monitors are VGA1 and DP3. Here is my config file:

```
bar-list = ["firstbar","secondbar"];
firstbar:{
    font: "Droid Sans";
    block-list: ["title"];
    position: "bottom";
    height: 20; 
    width: 1680;
    monitor: "DP3";
    title:{
        exec: "echo 'i am DP3'";
        align: "left";
        fixed-size: 90; 
        type: "persist"; 
    }   
}

secondbar:{
    font: "Droid Sans";
    block-list: ["title"];
    position: "bottom";
    height: 20; 
    width: 1680;
    monitor: "VGA1";
    title:{
        exec: "echo 'i am VGA1'";
        align: "left";
        fixed-size: 90; 
        type: "persist"; 
    }   
}
```

```
$ xrandr -q

Screen 0: minimum 320 x 200, current 3360 x 1050, maximum 8192 x 8192
LVDS1 connected (normal left inverted right x axis y axis)
   1600x900      59.99 +  40.00  
   1024x768      60.00  
   800x600       60.32    56.25  
   640x480       59.94  
VGA1 connected 1680x1050+0+0 (normal left inverted right x axis y axis) 473mm x 296mm
   1680x1050     59.95*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.08    60.00  
   800x600       75.00    60.32  
   640x480       75.00    60.00  
   720x400       70.08  
HDMI1 disconnected (normal left inverted right x axis y axis)
DP1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
HDMI3 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
DP3 connected 1680x1050+1680+0 (normal left inverted right x axis y axis) 473mm x 296mm
   1680x1050     59.95*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.08    60.00  
   800x600       75.00    60.32  
   640x480       75.00    60.00  
   720x400       70.08  
```

I think that with this config I should have one bar on each screen, however both bars are on the primary screen (VGA1).

Thanks in advance for your help

**Comment by geommer** [comment]
Hi @aanc, your config seems okay to me. I just need your help to track what is wrong because your issue is hard to understand from my computer. Can you apply that patch to your source and then build normally and run and show me what is printed on your terminal?

https://bpaste.net/show/49c38841b2db

just copy what is above in a file `p1.patch` then do:
* put it in `./src` 
* `cd ./src`
* `patch < p1.patch`
* `cd ..`
* `make clean`
* `make`
* `./yabar`

and then show me what is printed. It should be the list of active monitors and their dimensions and then exit without launching any bars.

**Comment by aanc** [comment]
Hi @geommer, I've done as you said, and here is the result:
```
$ ./yabar
VGA1 0 0 1680 1050
DP31 1680 0 1680 1050
```

It looks like a buffer issue, like if the `1` of `VGA1` was still in the buffer, as `DP3` is only 3 characters. Let me know if you need me to do other tests.

**Comment by geommer** [comment]
Hi @aanc, I think I figured out what is wrong now, please try to build yabar again after pulling the latest commit. If it is still not working, I will reopen the issue.

**Comment by aanc** [comment]
It works! Thanks :)
