### ISSUE TITLE
XMonad Workspaces

### ISSUE THREAD

**Issue by SageEx** [geommer/yabar#37]
Hi, can you or anyone tell me how to use yabar with XMonad workspaces ?

**Comment by SageEx** [comment]
More specifically how to format the colors and other attributes such that just ``cat``ing a file the block works ?

**Comment by nyasuh** [comment]
waiting for this

**Comment by EleDiaz** [comment]
In this moments, yabar works well with xmonad using EWMH config. But the current implementation only shows the current workspace. See #52 #58

**Comment by erebe** [comment]
I use yabar with xmonad, you just have to use a pipe to communicate with yabar
You need the tool "socat" in order for this to work
 
-- in your xmonad.hs
xmproc <- spawnPipe "socat unix-listen:/tmp/xmonad.sock,fork,reuseaddr stdio"
 xmonad $ defaults {
           logHook = dynamicLogWithPP $ xmobarPP { ppOutput          = hPutStrLn xmproc }

-- in your yabar.conf
workspaces: {
  exec: "socat unix-connect:/tmp/xmonad.sock stdio";
  type: "persist";
}

**Comment by SageEx** [comment]
Thanks
