### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by BasedArno** [geommer/yabar#38]
I cloned the project onto my computer and downloaded the required libraries. The linker fails with the error message:

```
ya_exec.c:(.text+0x14c4): undefined reference to `config_setting_lookup'
ya_exec.c:(.text+0x14f7): undefined reference to `config_setting_lookup'
collect2: error: ld returned 1 exit status
```

Using Ubuntu 14.04. All the necessary libraries are installed as far as I'm aware. Full make output (hopefully) attached: [makeoutput.txt](https://github.com/geommer/yabar/files/186725/makeoutput.txt).

**Comment by geommer** [comment]
Hi @BasedArno, I think this problem exists because Ubuntu 14.04 has an old version of libconfig (it is 1.4.x). You need to have libconfig>=1.5 in order to work.

**Comment by geommer** [comment]
I will close this issue. Please report if the above solution did not work (it should) for you and I will reopen the issue.
