### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by NoctuaNivalis** [geommer/yabar#40]
It'd be really cool if yabar would support images, like an option `icon: path` for a block which would show the icon on said path, and perhaps an `icon-exec: "command"` where the command should return the path to an icon, also executed in intervals/... . I'd be happy with just XBM/XPM support.

Especially the icon-exec would be useful, as that would allow dynamic images, like a battery icon or a wifi icon displaying battery/signal strenght.

(Am I correct in assuming the current screenshots use unicode glyphs for "icons"?)

**Comment by geommer** [comment]
Hi @NoctuaNivalis, I write this comment to say that I am interested in you request. I have been trying to figure out how to do this using cairo.

**Comment by geommer** [comment]
Well, a preliminary support for icons is now available with the last couple of commits using gdk-pixbuf and cairo. Here is an ugly working example:
https://i.imgur.com/15tKEjU.png

Please refer to block-specific options in README to know about the new icon options.

I will leave this issue open for a while to have more discussion and ideas about this interesting feature.
