### ISSUE TITLE
Inherit cannot find any other defined bar

### ISSUE THREAD

**Issue by Lindenk** [geommer/yabar#43]
When trying to use the 'inherit' options, regardless of bar naming, I can't seem to get yabar to find the referenced bar, which then results in yabar seg faulting. It's possible I could just be doing something wrong.

To help the debugging a bit, I've tried:

- Renaming all bars to not include special characters (like underscores)
- Have the referenced bar only act as an abstract bar and not be displayed
- Reverse the order of the bars

Here is my config: https://gist.github.com/Lindenk/2b85beafb47ff0b658a3

**Comment by geommer** [comment]
`inherit` just copies the bar-specific options from an already parsed bar to a successor one. It does not inherit all its blocks automatically. Maybe I can add another option to do that.

**Comment by geommer** [comment]
Also the current implementation behaves correctly only when the inherited bar precedes the new bar in the `bar-list` entry. Example:

bar-list: ["bar1", "bar2"]

bar1: {
     inherit: "bar2"
}
is not useful currently.

**Comment by Lindenk** [comment]
Ah, ok. I'll try that instead.

**Comment by geommer** [comment]
I've add a new bar-specific option `inherit-all`. You can now for example type:
bar2: {
inherit-all: "bar1"
}
