### ISSUE TITLE
make failed ya_config_parse

### ISSUE THREAD

**Issue by ColdSauce** [geommer/yabar#44]
I'm running Debian. When I try to make yabar, it's giving me the following error:

<code>cc -o yabar src/ya_parse.o src/ya_exec.o src/ya_draw.o src/ya_main.o src/intern_blks/ya_intern.o -lxcb -lpthread -lxcb-randr `pkg-config --libs pango pangocairo libconfig`
src/ya_parse.o: In function `ya_config_parse':
ya_parse.c:(.text+0x8b3): undefined reference to `config_setting_lookup'
ya_parse.c:(.text+0x9db): undefined reference to `config_setting_lookup'
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'yabar' failed
make: *** [yabar] Error 1</code>

**Comment by ColdSauce** [comment]
Sorry, I just saw another issue with the same problem.

My bad.

**Comment by geommer** [comment]
Hi @ColdSauce, I checked out libconfig's changelog to understand the changes that happened after 1.5. It seems there is only one function rename. So I added a new flag (not in the master makefile) called DYA_INTERNAL. So please build the source code with the latest commit and then build it using `make CPPFLAGS=-DYA_INTERNAL` instead the ordinary `make`. Please tell me if it works well now.
