### ISSUE TITLE
Feature Request: Add spacers

### ISSUE THREAD

**Issue by NBonaparte** [geommer/yabar#46]
In Conky, there is a setting called `use_spacer` which adds spaces around numerical values to prevent them from moving, compared to normal (i.e. when CPU usage goes from 9 to 10%, for example, the whole text shifts to the left or right depending on text centering). Could we have a setting for this in the form of `spacer: #`, where # is the largest length and `# - number_length` spaces are added to the left of the number?

**Comment by geommer** [comment]
Fixed by #47.
