### ISSUE TITLE
let blocks use bar backgroundcolor

### ISSUE THREAD

**Issue by blendi-93** [geommer/yabar#49]
if i set no bgcolor for my block it uses black.
Is it possible to define default bacground color for blocks or let blocks without bgcolor use bar bg color?

my current config

    bar-list = ["topbar"];
    topbar:{
    	font: "Droid Sans, FontAwesome Bold 9";
    	block-list: ["desktop", "title", "date"];
    	position: "top";
    	height: 24; 
    	//If you want transparency, use argb, not rgb
    	background-color-rgb: 0x1c2126;
    	foreground-color-rgb: 0xffffff;
    	underline-size: 2;
    	overline-size: 0;
    	slack-size: 4;
    	desktop:{
    		exec: "bspc subscribe report";
    		align: "left";
    		fixed-size: 120;
    		type: "persist";
    		justify: "left";
    	}
    	title:{
    		exec: "xtitle -s";
    		align: "left";
    		fixed-size: 350;
    		type: "persist";
    		justify: "left";
    	}
    	date:{
    		exec: "date +'%a %d %b, %I:%M'";
    		align: "right";
    		fixed-size: 150;
    		type: "periodic"; 
    		interval: 1; 
    	}
    }

**Comment by geommer** [comment]
You are absolutely right. That was the intended behavior from the initial commit. But the dynamic color parsing feature altered that. Now I think it is fixed with the latest commit. If it is not working for you please report it and I will reopen the issue.
