### ISSUE TITLE
[featurerequest] different collors in one block

### ISSUE THREAD

**Issue by blendi-93** [geommer/yabar#50]
i need multiple colors in one block (shuld display workspaces)

using this i get reg fg and the other color printet to panel:

    Y fg 0xffff0000 Y!red !Y fg 0xff00ff00 Y!green !Y fg 0xff0000ff Y!blue'

sample config to reproduce:

    bar-list = ["topbar"];
    topbar:{
    	font: "Droid Sans, FontAwesome Bold 9";
    	block-list: ["rgb"];
    	position: "top";
    	height: 24; 
    	//If you want transparency, use argb, not rgb
    	background-color-rgb: 0x1c2126;
    	foreground-color-rgb: 0xffffff;
    	underline-size: 2;
    	overline-size: 0;
    	slack-size: 4;
    	rgb:{
    		exec: "echo '!Y fg 0xffff0000 Y!red !Y fg 0xff00ff00 Y!green !Y fg 0xff0000ff Y!blue'";
    		align: "right";
    		fixed-size: 340;
    		type: "once"; 
    		interval: 1; 
    	}
    }

**Comment by geommer** [comment]
That can be easily done using pango markup. I recommend you read [this page](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html).
For example:
`exec: "echo '<span foreground=\"blue\">Blue</span><span foreground=\"red\"> Red</span>'";
pango-markup: true;
type: "once";`

 The `fg` entry is actually redundant to pango syntax and should be used for the easy cases (i.e. single color).

**Comment by blendi-93** [comment]
Thanks for the link and example this makes it cleaner, now it works as i want.
