### ISSUE TITLE
Wiki Documentation

### ISSUE THREAD

**Issue by SethBarberee** [geommer/yabar#56]
I think that it would be helpful for new users if we had a tutorial or quick start guide on the wiki. It also can store in for on how each block affects the output of you want.

**Comment by geommer** [comment]
This would be useful. I think the README has a wiki-like style but I admit it is very long for the impatient newcomers. A wiki will be added in the upcoming days.

**Comment by NBonaparte** [comment]
Wiki has been added.

**Comment by jacksgt** [comment]
Thanks for porting this over @NBonaparte !
