### ISSUE TITLE
Cant seem to get this to make install on debian?

### ISSUE THREAD

**Issue by dahjin** [geommer/yabar#57]
I'm getting 
No package 'gdk-pixbuf-2.0' found
same with pango.h

**Comment by geommer** [comment]
Hi @dahjin, please try the name `libgdk-pixbuf2.0` instead.

**Comment by dahjin** [comment]
All of them are updated. I followed the installation to the letter. Not sure if it is detecting my libs.

**Comment by dahjin** [comment]
Now getting undefined reference to 'config_setting_lookup' when running make.

**Comment by dahjin** [comment]
➜  yabar git:(master) make
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-30-ga681a25\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/ya_parse.o src/ya_parse.c
src/ya_parse.c: In function ‘ya_config_parse’:
src/ya_parse.c:743:3: warning: implicit declaration of function ‘config_setting_lookup’ [-Wimplicit-function-declaration]
   blklist_set = config_setting_lookup(curbar_set, "block-list");
   ^
src/ya_parse.c:743:15: warning: assignment makes pointer from integer without a cast
   blklist_set = config_setting_lookup(curbar_set, "block-list");
               ^
src/ya_parse.c:762:15: warning: assignment makes pointer from integer without a cast
    curblk_set = config_setting_lookup(curbar_set, blkstr);
               ^
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-30-ga681a25\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/ya_exec.o src/ya_exec.c
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-30-ga681a25\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/ya_draw.o src/ya_draw.c
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-30-ga681a25\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/ya_main.o src/ya_main.c
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-30-ga681a25\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/intern_blks/ya_intern.o src/intern_blks/ya_intern.c
cc -o yabar src/ya_parse.o src/ya_exec.o src/ya_draw.o src/ya_main.o src/intern_blks/ya_intern.o -lxcb -lpthread -lxcb-randr -lxcb-ewmh `pkg-config --libs pango pangocairo libconfig gdk-pixbuf-2.0`
src/ya_parse.o: In function `ya_config_parse':
ya_parse.c:(.text+0x482): undefined reference to `config_setting_lookup'
ya_parse.c:(.text+0xaef): undefined reference to `config_setting_lookup'
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'yabar' failed
make: *** [yabar] Error 1

**Comment by dahjin** [comment]
http://pastebin.com/wq1QbD7c

**Comment by geommer** [comment]
Hi @dahjin, I don't know what happened to your first issue (that one about the package `gdk-pixbuf`), but it seems it is solved after you installed the right package name, the second issue (i.e. undefined reference to `config_setting_lookup`) can be solved using the command `export CPPFLAGS=-DOLD_LIBCONFIG` then invoke `make`. You may need to invoke `make clean` before those two commands to remove the old object files.

**Comment by dahjin** [comment]
Worked like a charm. Thanks!
