### ISSUE TITLE
Workspace list with highlighting

### ISSUE THREAD

**Issue by Gingernaut** [geommer/yabar#58]
In your internal config example, the ya_ws has different icons to represent the current workstation. It would be fantastic to be able to have all open workspaces listed with a highlight or color block over the workspace that is currently open.

**Comment by geommer** [comment]
Hi @Gingernaut, I think your request is the same as #52. This feature is on my priorities but I first need to to make sure that the variable-width feature is robust enough so it can be used to develop this feature.
