### ISSUE TITLE
i3bar and YABAR_WORKSPACE

### ISSUE THREAD

**Issue by hansol-shin** [geommer/yabar#63]
I'm having some trouble configuring YABAR_WORKSPACE to work like i3bar.
The problem (whether a bug or not) is that, say I have 10 workspaces from 1 to 0.
And I create a window in workspace 1 and 2.
Now I want to create a window in workspace 9.
YABAR_WORKSPACE somehow gets buggy about how it shows the title of the workspace.
If I skipped workspace 3, then workspace 9 will have '3' instead of '9'...

In another word, yabar assumes that the user will only create windows in workspaces in order, not in a random sequence directed by the user.

EDIT: I got a work around using a script.
Also, is there any way to tweak the yabar.conf to change the color accordingly to `i3-msg -t get_workspaces' output?
My goal is to display all of my available workspaces on the left of my yabar.
Then to change the bg fg colors of the block that's being focused by i3 to a different color.

**Comment by hansol-shin** [comment]
I got a work around using a script.

**Comment by hansol-shin** [comment]
Is there any way to tweak the yabar.conf to change the color accordingly to `i3-msg -t get_workspaces' output?
My goal is to display all of my available workspaces on the left of my yabar.
Then to change the bg fg colors of the block that's being focused by i3 to a different color.

**Comment by apheleia** [comment]
See #21 for a solution to this exact requirement (workspaces and colours).

**Comment by hansol-shin** [comment]
@apheleia Thanks. I will try with pongo markup.

**Comment by geommer** [comment]
A i3-like internal workspace block will solve all these frequent questions about this issue. I just need sometime because I am very busy at the moment. I need first to make sure that the variable-width feature works well because this internal workspace block will contain several blocks that will appear/disappear on workspace change and that needs a robust variable-width support.

**Comment by geommer** [comment]
Please refer to #52 to know any news about this issue.
