### ISSUE TITLE
Multiple blocks with one configured block

### ISSUE THREAD

**Issue by roveo** [geommer/yabar#66]
I'm trying to get yabar to work with i3, and it's been very nice so far, but now I want to add workspace support similar to i3bar.

I can generate a list of workspaces from `i3-msg -t get_workspaces` json output, but I can't display them in the bar the way I want: each workspace as a separate block, while hiding non-active workspaces and with different underline/overline/background/foreground depending on the workspaces' state.

Here's how I see it:
In the config, it should look just like a usual block, except that the command outputs several lines instead of a single one. For example, command `seq 1 10` would give us 10 blocks from 1 to 10.

And then, the usual formatting is also applied to each of the resulting blocks, so this for example:
```
1
"!Y u0xff0000 Y!2"
3
```
would give us 3 blocks, block `2` with red underline, the rest with default settings (inherited from the block/bar).

Command button actions can be then handled with a new env variable `${YABAR_BLOCK_NAME}` containing block text stripped of `!Y..Y!` formatting.

**Comment by geommer** [comment]
Hi @roveo, yabar currently parses what is inside "!Y xxxxx Y!" only if you put it just once at the beginning of your string output. A suggested solution to what you want to do is to use pango markup.
Untest example:

`1 <span underline="red" size="100">3</span>`

as yabar can parse and render pango markup using the option `pango-markup: true;`.
for more info about pango markup, visit this [page](https://developer.gnome.org/pygtk/stable/pango-markup-language.html).

**Comment by roveo** [comment]
Hi @geommer! Thanks for suggesting pango (and for yabar of course), I'll try it out.

Still would be nice to be able to generate separate blocks if you want to have gaps between items for example.
