### ISSUE TITLE
Can't display font awesome in yabar

### ISSUE THREAD

**Issue by noptx** [geommer/yabar#67]
I use bspwm and will add yabar for my panel,yabar only can display Font Awesome then i try font awesome in internal-prefix and cannot display the icon.

**Comment by geommer** [comment]
Hi @noptx, your problem is weird because most yabar users (including me) use font awesome in internal and external blocks without problem. I suggest it may be related to correctly copying the utf character to your `yabar.conf` file using your text editor (vim, atom, etc...).

**Comment by noptx** [comment]
hhmm i forgot it,i m sorry.
