### ISSUE TITLE
Yabar blocks missing after application full screens. 

### ISSUE THREAD

**Issue by nmiculinic** [geommer/yabar#71]
After application goes full screen and back it takes around 5 seconds (not all blocks at the same time) for the blocks to return to their original state. 

Not all of them do though, I have two blocks simulating gaps (having maximum opacity), but after return from full screen their opacity is gone and they aren't transparent anymore, but having default background color.

**Comment by nmiculinic** [comment]
After bit more poking, it's due to periodic components. 

Gap blocks (since gap-horizontal weren't working for me to be invisible) were once, and when putting them to periodic now they work fine (after one interval period)

**Comment by geommer** [comment]
Sorry @nmiculinic, I haven't noticed this issue until now. Are you using the `master` branch or the `dev_var_width` branch? This is a bug in `dev_var_width` and that is the only reason why I haven't merged this branch to `master`. The time may be the periodic time for each block until it refreshes itself with the other background color. Actually, with the current source code this bug mostly appears only at yabar startup and disappears after opening and closing the first window.

**Comment by nmiculinic** [comment]
I think I'm using master, ```yabar v0.4.0-32-gc7881b2```

**Comment by ccwolf64** [comment]
I am also having this problem on the master branch. I have several `persist` blocks that monitor things like volume or music and they only reappear once the output of the command is updated. I also have some `periodic` blocks but they seem to be fine - it is just the `persist` blocks for me. This happens every time I close a full screen window - not just at startup.

I am running Ubuntu 16.04 if that affects anything

**Comment by wesbluemarine** [comment]
I have the same issue with bspwm after startx and after windows back from fullscreen

**Comment by NickVst** [comment]
Similar issue using i3wm and compton, using yabar version 0.4.0 from the AUR.

[Here is a gist](https://gist.github.com/NickVst/ce29d313edde9741b29107caa4d886f1) that's useful for testing the difference between the effect of static and periodically updating blocks.

The effect for me seems to be this.

### Static blocks
- Background color resorts to background color of the underlying bar.
- Text becomes non-existent. 
- This means that the entire block is basically invisible.

### Updated blocks
- Background color is underlying bar's, until an update takes place.
- Text does not appear, until an update takes place.
- Block becomes visible on update.
- Block also becomes visible if the update simply posts the same line as before. E.G. a block that fires off `echo ''` once does not work, but a block that fires off `echo ''` periodically does work on the next update.

**Comment by NBonaparte** [comment]
Should be fixed since 227a0ec, as now it redraws on exposure.
Feel free to reopen if this is still an issue.
