### ISSUE TITLE
Cannot choose monitor based on setup

### ISSUE THREAD

**Issue by apheleia** [geommer/yabar#73]
Dear George,

I have a laptop setup which I use in combination with an external monitor at work. It is easy to setup yabar to show on either the built-in screen (`LVDS1`) or the external monitor (`HDMI2`)

I want yabar to display on `HDMI2` when it is connected, and on `LVDS1` otherwise. Is it possible to pass a script or command to the `monitor` setting of yabar?

Is a workaround possible where I always display yabar on both monitors, and only `LVDS1` if `HDMI2` is not connected?

Important is that the bar shows on `HDMI2` if connected and on `LVDS1` if `HDMI2` is not connected.

I use i3 with arch.

Cheers!

**Comment by geommer** [comment]
Hi @apheleia, currently yabar only checks for connected monitors at startup. That makes it impossible to dynamically move between monitors if you unplug/plug some monitor throughout runtime. But I like the idea (I frankly can't figure out how exactly this can be done currently) and this will be labelled as a feature request.

**Comment by apheleia** [comment]
Thanks. Can I (as a workaround) have two bars (one on each screen) or will yabar crash if the second screen for the second bar is missing?

**Comment by cmiles74** [comment]
I'm also working with a a laptop that docks and undocks. I don't mind restarting yabar when the screen configuration changes (I can set that up to happen automatically), but it looks like if the monitor for a bar is missing, yabar just sticks it on an available monitor. When I unplug, I end up with two stacked bars.

Could yabar ignore a bar if the monitor specified isn't present?

Thank you!

**Comment by apheleia** [comment]
Same for me. I'd prefer if the bar doesn't show in case a monitor doesn't exist.

**Comment by cstich** [comment]
@apheleia Is there any chance to expose a `monitor` flag when starting `yabar`. Something like `yabar -montior DP2-1` would be great IMHO.

I also second the request to don't show a bar in case a monitor doesn't exist, or at least have the option of that behavior.

**Comment by apheleia** [comment]
The workaround I use currently is the following:
I set the monitor to `monitor: "HDMI2";`. When there is no `HDMI2` connected, the yabar automatically shows on the laptop screen instead. (see also the comment by @cmiles74)

I don't know if that is an intended feature, though ...

What that means is that I will always have exactly one yabar, either on HDMI or on built-in.

**Comment by NBonaparte** [comment]
Hi everyone, 388d950 implements fallback monitors specified by `monitor-fallback`. It also reloads the whole program when a randr screen change is detected. Please see if these changes fit your use cases, and if not, suggest any other changes.
