### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by z1lt0id** [geommer/yabar#8]
I'm going to make a Gentoo ebuild for this but would like to confirm what exact dependencies Yabar requires?  Maybe include them in the README?

**Comment by geommer** [comment]
You need pango, cairo and libconfig. I will create a dependencies file to make it easier for users very soon.

**Comment by nandeska** [comment]
You should precise libconfig >= 1.5 because on older versions, config_setting_lookup() is named config_setting_lookup_from() and it leads to compilations errors (debian stable has libconfig 1.4.9).

**Comment by genkiel** [comment]
For anyone stumbling on the issue, without resurrecting it: On gentoo you also need wireless-tools (libiw) & asciidoc to compile z1lt0id's ebuild.

**Comment by z1lt0id** [comment]
I would ressurect it, but unfortunately I haven't been using Gentoo for
quite some time.
