### ISSUE TITLE
Graphical glitches 

### ISSUE THREAD

**Issue by Fabiuz99** [geommer/yabar#83]
Hi, I'm facing some graphical glitches after I change workspace or exit from fullscreen (especially with mpv).
It seems that some parts of the bar disapppear for few seconds
[Here](https://github.com/Fabiuz99/Ah_Boh/blob/master/Config/yabar.conf) is my config file
![2016-06-17-15 34 32-screenshot](https://cloud.githubusercontent.com/assets/12954989/16152371/e4f4a202-34a1-11e6-8630-ab2a729e5176.png)
![2016-06-17-15 42 44-screenshot](https://cloud.githubusercontent.com/assets/12954989/16152436/3b2a5108-34a2-11e6-8d0a-c19847496c26.png)

**Comment by geommer** [comment]
Hi @Fabiuz99, I think this may be the same bug in #71. Please read the issue and kindly reply to my comments there.

**Comment by Fabiuz99** [comment]
Hi, this is similar but in my pc it happens even if i change workspace and I have no gaps actived. In my case the main problem is that parts of the bar become transparent and just rarely some blocks disappear

**Comment by NBonaparte** [comment]
Does 227a0ec fix this? It should redraw on expose events now.

**Comment by NBonaparte** [comment]
Closing because it *should* be fixed, please reopen if it isn't.
