### ISSUE TITLE
Yabar crashes when opening spotify from bar

### ISSUE THREAD

**Issue by Gingernaut** [geommer/yabar#86]
When I open spotify (installed from the AUR) by clicking on the spotify icon in my dock (docky), yabar crashes. This does not happen with any other application. It works if I open spotify via Rofi. 

When I run yabar from the command line then click on the spotify icon, yabar crashes and I get the following error message:

`[1]    3367 segmentation fault (core dumped)  yabar`

The numeric value is different every time but the rest of the error message stays the same.

**Comment by geommer** [comment]
Hi @Gingernaut and sorry for the late response. It seems you use the stable version. Please install install the package `yabar-git` instead from AUR. This was a bug that was solved by #69.
