### ISSUE TITLE
Transparency not working

### ISSUE THREAD

**Issue by lycurgus** [geommer/yabar#87]
For some reason I can't seem to get transparency working. I'm on the latest git (pulled a few days ago), with the following (test) configuration:

`bar-list: ["bar"];`

`bar: {`
`    background-color-argb: 0x88888888;`
`    block-list: ["time"];`
`    time: {`
`        exec: "date +'%^a %Y-%m-%d %H:%M:%S'";`
`        align: "right";`
`        fixed-size: 180;`
`        type: "periodic";`
`        interval: 1;`
`        foreground-color-rgb:0x92D8F0;`
`        underline-color-rgb:0xc0b929;`
`    }`
`}`

I'm running as a user, from the build directory (i.e. I ran `make` but not `make install`), but `sudo` doesn't appear to help.

Have I missed something glaringly obvious here? There is no visible difference between `background-color-argb: 0x88888888;` and `background-color-rgb: 0x888888;`...

(edit, days later: it's probably worth mentioning that i'm using i3 under Fedora 24)

**Comment by huffstler** [comment]
Does everything else defined in the bar appear correct?

If so, It may be because you picked a transparency value that doesn't change the color that much. Try comparing 0x00888888 & 0xFF888888 to 0x888888, and come back and let us know if there's still no difference.

Also, I'm assuming your wallpaper isn't a similar shade of grey either right? Because that could also be a factor in not being able to differentiate.

**Comment by lycurgus** [comment]
Yep, everything else looks okay as far as I can tell.

Changing the transparency doesn't seem to help either - I should have mentioned, but the 0x88 example above is just what I had after trying both 0x00 and 0xff without success (and because I can never seem to remember if "full alpha" means fully transparent or fully opaque... so I picked a halfway value). Running three bars side-by-side, one with 0x88888888, one with 0xff888888, and one with 0x888888, results in three identical bars.

The wallpaper is definitely not grey - there's colour and variation under where the bar is displaying (as well as elsewhere).

Also, just confirmed that `make install`ing didn't change anything.

**Comment by huffstler** [comment]
Last easy thing that I can think of is that the transparency may rely on you having a compositor installed, Like compton or compiz. Do you have one of those?

**Comment by lycurgus** [comment]
I didn't, and installing one (and rebooting for good measure) didn't appear to change anything. I didn't do any configuration of compiz itself, though - would that have been necessary?

I'm not sure if it's relevant but I do have transparency working on urxvt already, so it doesn't seem like anything should be stopping yabar from doing it too...

**Comment by lycurgus** [comment]
Ok, turns out the missing part of the equation was installing and running `xcompmgr`. Transparency's working now :D
