### ISSUE TITLE
Yabar Starting in Middle of Screen

### ISSUE THREAD

**Issue by ibrokemypie** [geommer/yabar#96]
I can attatch my config file if needed, and yabar is at the end of my autostart file (openbox) as `yabar &`

![2016-07-09-073424_1280x800_scrot](https://cloud.githubusercontent.com/assets/7827846/16686239/25436c90-4554-11e6-88ab-c76da6447a4d.png)

this is what occors upon startx

![2016-07-09-073507_1280x800_scrot](https://cloud.githubusercontent.com/assets/7827846/16686240/25d24b22-4554-11e6-8e43-8af91f101900.png)

this is what it should looklike.

killing the yabar process and starting it again results in odd locations for the bar, either in the middle, above the top of the highest window, or if the highest window is less than the bar height from the top of the screen, somewhere near the middle again.

**Comment by NBonaparte** [comment]
Fixed by #92.
