### ISSUE TITLE
New Feature: Language-agnostic Custom Blocks

### ISSUE THREAD

**Issue by coxley** [geommer/yabar#97]
Would love to leave i3bar + i3status to try yabar out but I have several custom modules written that are important. (things for work and personal things that aren't general purpose for contributing to any project)

Looking through the documentation and issues I didn't see this one raised. I think it's important for the reasons above + patching the project in C to add some custom blocks would be less than fun. :)

**Comment by jacksgt** [comment]
I am not quite sure what you mean:
Should yabar ship with non-C blocks by default or do you simply want to run / execute your own scripts and binaries?
The latter one is already possible. Just give yabar a path to the appropriate file in 'exec' and it will execute it for you: https://github.com/geommer/yabar#block-specific-options

**Comment by coxley** [comment]
@jacksgt I am sorry, obviously I missed that. Thank you, closing this then! :)

**Comment by jacksgt** [comment]
As this is solved, either @geommer or @coxley please close this issue.
